#include "goldsrc_usercmd_test_fixture.hpp"
#include <algorithm>
#include <catch2/catch_test_macros.hpp>
#include <hlclient/goldsrc/bit_reader.hpp>
#include <hlclient/goldsrc/delta_value_decoder.hpp>
#include <hlclient/goldsrc/reference_client_move.hpp>
#include <limits>
#include <sstream>

namespace {
namespace g = hlclient::goldsrc;
std::vector<std::byte> hex(std::string_view text) {
    std::istringstream input{std::string{text}};
    std::vector<std::byte> bytes;
    unsigned value = 0;
    while (input >> std::hex >> value)
        bytes.push_back(static_cast<std::byte>(value));
    return bytes;
}
g::GoldSrcUserCmdSchemaBinding binding() {
    // Independently stated existing test descriptors, not the production factory.
    auto registry = hlclient::test::usercmd_fixture::exact_registry();
    auto bound = g::bind_goldsrc_usercmd_schema(
        registry,
        g::GoldSrcUserCmdSchemaBindingProfile::public_goldsrc48_usercmd_schema_v1);
    REQUIRE(bound);
    return std::move(*bound.binding);
}
g::GoldSrcWireUserCmd edge_command() {
    g::GoldSrcWireUserCmd c;
    c.lerp_msec = 511;
    c.angle_turns = {32768, 16384, 65535};
    c.buttons = 65535;
    c.forward = -400;
    c.side = 400;
    c.up = -1;
    c.light_level = 255;
    c.impulse = 255;
    c.impact_index = 63;
    c.impact_eighths = {-32767, 32767, -1};
    return c;
}
// Independently assembled LSB bit strings, per-command padding and CRC32
// literals calculated outside production code. Not copied from a capture or
// generated by the encoder under test. Three commands: edge(msec=0), then
// msec=255 only, then all-zero; backup/new=1/2, seq=0x11223344.
constexpr std::string_view complex_wire =
    "02 39 87 bf 0b 40 d0 4f 46 ea ea f0 e1 51 11 7f ae 63 0a ea ae 41 26 aa b6 ae aa "
    "0f 59 fe aa e5 06 f9 44 45 01 02 ea 47 09 41 55 4f 41 01 55 07 01 11 15 45 11 41 "
    "55 55 41 01 55 00";
constexpr std::string_view complex_body =
    "85 01 02 ea ff fb 0f 00 04 00 f8 ff 1f 32 ff 20 33 00 ff ff ff ff ff bf ff ff 00 "
    "00 11 f8 07 fa ff 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 "
    "00 00 00";
} // namespace

TEST_CASE("Reference move checksum and munging match independent byte literals",
          "[goldsrc][usercmd][reference-move][literal]") {
    const g::GoldSrcMoveChecksum crc{
        g::GoldSrcMoveChecksumProfile::public_goldsrc48_crc32_low8_v1, 8192};
    const auto zero = hex("00 00 01 00");
    REQUIRE(crc.compute({0, 32}, zero));
    CHECK(*crc.compute({0, 32}, zero).checksum == 0xcc);
    CHECK(*crc.compute({7, 32}, zero).checksum == 0x8c);
    CHECK(*crc.compute({1020, 32}, zero).checksum == 0xcc);
    CHECK(*crc.compute({0, 32}, hex("01 00 01 00")).checksum == 0x52);
    const auto empty_commands = hex("00 00 00");
    CHECK(*crc.compute({1021, 24}, empty_commands).checksum == 0x0f);
    auto body = hex(complex_body);
    CHECK(*crc.compute({0x11223344, body.size() * 8}, body).checksum == 0x87);
    REQUIRE(g::transform_reference_move_body(body, body.size(), 0x11223344, false));
    const auto wire = hex(complex_wire);
    CHECK(std::equal(body.begin(), body.end(), wire.begin() + 3, wire.end()));
    REQUIRE(g::transform_reference_move_body(body, body.size(), 0x11223344, true));
    CHECK(body == hex(complex_body));
    for (std::size_t length = 0; length <= 255; ++length) {
        std::vector<std::byte> value(260, std::byte{0x73});
        const auto original = value;
        REQUIRE(g::transform_reference_move_body(value, length, 0x3fffffff, false));
        CHECK(std::equal(
            value.begin() + static_cast<std::ptrdiff_t>(length / 4 * 4), value.end(),
            original.begin() + static_cast<std::ptrdiff_t>(length / 4 * 4)));
        REQUIRE(g::transform_reference_move_body(value, length, 0x3fffffff, true));
        CHECK(value == original);
    }
    std::vector<std::byte> long_body(64, std::byte{1});
    const auto before = crc.compute({1020, 512}, long_body);
    long_body[63] = std::byte{2};
    CHECK(crc.compute({1020, 512}, long_body).checksum == before.checksum);
    CHECK(before.covered_bytes ==
          60); // A short capped check cannot detect every mutation.
    CHECK_FALSE(crc.compute({0x80000000, 32}, zero));
    CHECK_FALSE(crc.compute({1, 31}, zero));
    CHECK_FALSE(g::transform_reference_move_body(body, 256, 0, false));
}

TEST_CASE(
    "Reference codec decodes and constructs independently authored command chains",
    "[goldsrc][usercmd][reference-move][literal]") {
    const g::GoldSrcReferenceClientMoveCodec codec{binding(), 7};
    g::ReferenceMoveSource source;
    source.generation = 7;
    source.sequence = 0x11223344;
    source.delivery_ordinal = 42;
    source.payload_ordinal = 19;
    source.reliable = true;
    auto wire = hex(complex_wire);
    const auto decoded = codec.decode(wire, 0, source);
    REQUIRE(decoded);
    CHECK(decoded.message->source == source);
    CHECK(decoded.message->checksum_matched);
    CHECK(decoded.message->loss_metadata == 0x85);
    CHECK(decoded.message->backup_count == 1);
    CHECK(decoded.message->new_count == 2);
    CHECK(decoded.message->end_byte == wire.size());
    REQUIRE(decoded.message->commands.size() == 3);
    auto a = edge_command();
    auto b = a;
    b.msec = 255;
    CHECK(decoded.message->commands[0].value == a);
    CHECK(decoded.message->commands[1].value == b);
    CHECK(decoded.message->commands[2].value == g::GoldSrcWireUserCmd{});
    CHECK(decoded.message->commands[0].backup);
    CHECK_FALSE(decoded.message->commands[1].backup);
    CHECK(decoded.message->commands[0].start_bit == 48);
    CHECK(decoded.message->commands[0].end_bit == 248);
    CHECK(decoded.message->commands[1].start_bit == 248);
    CHECK(decoded.message->commands[1].end_bit == 272);
    const std::array commands{a, b, g::GoldSrcWireUserCmd{}};
    const auto encoded = codec.encode(commands, 1, 0x85, source);
    REQUIRE(encoded);
    CHECK(encoded.message->bytes == wire);
    wire.clear();
    CHECK(decoded.message->commands[0].value.forward == -400);
    CHECK(decoded.message->commands[0].value.buttons == 65535);
    CHECK(g::quantize_wire_angle(-90) == 49152);
    CHECK(g::quantize_wire_angle(360) == 0);
    CHECK(g::quantize_wire_movement(-1.9) == -1);
    CHECK_FALSE(g::quantize_wire_movement(-2048));
    CHECK_FALSE(g::quantize_wire_angle(std::numeric_limits<double>::infinity()));
}

TEST_CASE("Reference move counts limits zero duration and saturated transform length "
          "stay separate",
          "[goldsrc][usercmd][reference-move][bounds]") {
    const g::GoldSrcReferenceClientMoveCodec codec{binding(), 1};
    g::ReferenceMoveSource source;
    auto zero = hex("02 04 cc 00 19 50 00");
    const auto decoded = codec.decode(zero, 0, source);
    REQUIRE(decoded);
    CHECK(decoded.message->commands[0].value.msec == 0);
    std::array<g::GoldSrcWireUserCmd, 1> one{};
    CHECK(codec.encode(one, 0, 0, source).message->bytes == zero);
    source.sequence = 1021;
    const auto none = codec.decode(hex("02 03 0f 00 00 00"), 0, source);
    REQUIRE(none);
    CHECK(none.message->commands.empty());
    CHECK(codec.encode({}, 0, 0, source).message->bytes == hex("02 03 0f 00 00 00"));
    for (std::size_t count = 0; count <= 62; ++count) {
        std::vector<g::GoldSrcWireUserCmd> commands(count);
        for (std::size_t i = 0; i < count; ++i)
            if ((i % 2) == 0)
                commands[i] = edge_command();
        for (const auto backups : std::array<std::size_t, 3>{0, count / 2, count}) {
            const auto encoded = codec.encode(commands, backups, 0xff, source);
            REQUIRE(encoded);
            const auto read = codec.decode(encoded.message->bytes, 0, source);
            REQUIRE(read);
            CHECK(read.message->backup_count == backups);
            CHECK(read.message->new_count == count - backups);
            if (encoded.message->bytes.size() > 258)
                CHECK(read.message->transform_length == 255);
            REQUIRE(read.message->commands.size() == commands.size());
            for (std::size_t i = 0; i < count; ++i)
                CHECK(read.message->commands[i].value == commands[i]);
        }
    }
    std::vector<g::GoldSrcWireUserCmd> too_many(63);
    CHECK_FALSE(codec.encode(too_many, 0, 0, source));
    CHECK_FALSE(codec.encode(one, 2, 0, source));
    one[0].forward = -2048;
    CHECK_FALSE(codec.encode(one, 0, 0, source));
    one[0] = {};
    one[0].impact_eighths[0] = 1;
    CHECK(codec.encode(one, 0, 0, source)); // Not simulation's coupled impact policy.
    const g::GoldSrcReferenceClientMoveCodec tiny{binding(), 1, {1, 6, 1}};
    CHECK_FALSE(tiny.encode(one, 0, 0, source));
    source.generation = 2;
    CHECK_FALSE(codec.encode({}, 0, 0, source));
    CHECK_FALSE(codec.decode(zero, 0, source));
    const g::GoldSrcReferenceClientMoveCodec invalid{binding(), 0};
    CHECK_FALSE(invalid.valid_configuration());
}

TEST_CASE("Reference move critical truncations masks padding and checksums fail "
          "transactionally",
          "[goldsrc][usercmd][reference-move][negative]") {
    const g::GoldSrcReferenceClientMoveCodec codec{binding(), 1};
    g::ReferenceMoveSource source;
    source.sequence = 0x11223344;
    const auto literal = hex(complex_wire);
    for (std::size_t size = 0; size < literal.size(); ++size) {
        const auto failed = codec.decode(std::span{literal}.first(size), 0, source);
        CHECK_FALSE(failed);
        CHECK_FALSE(failed.message);
    }
    auto bad = literal;
    bad[2] ^= std::byte{1};
    const auto checksum = codec.decode(bad, 0, source);
    REQUIRE(checksum.error);
    CHECK(checksum.error->code == g::ReferenceMoveErrorCode::checksum_mismatch);
    bad = literal;
    bad[1] = std::byte{0};
    CHECK_FALSE(codec.decode(bad, 0, source));
    bad = literal;
    bad[0] = std::byte{3};
    CHECK_FALSE(codec.decode(bad, 0, source));
    source.sequence =
        0; // Own minimal literals: transform changes only complete 4-byte blocks.
    for (const auto text : {"02 04 cc 08 19 50 00", // nonzero padding in zero command
                            "02 04 cc 03 19 50 00", // mask-byte count=3, beyond schema
                            "02 04 cc 07 19 50 00"}) {
        CHECK_FALSE(codec.decode(hex(text), 0, source));
    }
    auto short_mask = hex("02 06 00 00 00 01 fa ff 07");
    REQUIRE(g::transform_reference_move_body(std::span{short_mask}.subspan(3), 6, 0,
                                             false));
    CHECK_FALSE(
        codec.decode(short_mask, 0, source)); // field 15 outside 15-field schema
    auto counts = hex("02 03 00 00 00 3f");
    const auto rejected = codec.decode(counts, 0, source);
    REQUIRE(rejected.error);
    CHECK(rejected.error->code == g::ReferenceMoveErrorCode::count_limit);
    const auto padding = codec.decode(hex("02 04 cc 08 19 50 00"), 0, source);
    REQUIRE(padding.error);
    CHECK(padding.error->code == g::ReferenceMoveErrorCode::nonzero_padding);
    const auto schema = binding();
    constexpr auto profile =
        g::DeltaValueCompatibilityProfile::public_goldsrc48_usercmd_delta_v1;
    const auto base = g::DeltaObjectBuilder{{}, profile}.build_default(schema.schema());
    REQUIRE(base);
    const auto body = hex(complex_body);
    for (std::size_t bits = 0; bits < 198; ++bits) {
        CHECK_FALSE(g::GoldSrcDeltaValueDecoder{{}, profile}.decode_delta(
            schema.schema(), &*base.state, {body, 24, bits, {}, {}, false}));
    }
    CHECK(g::GoldSrcDeltaValueDecoder{{}, profile}.decode_delta(
        schema.schema(), &*base.state, {body, 24, 198, {}, {}, false}));
}

TEST_CASE("Client move walker retains exact framing alongside inert reliable controls",
          "[goldsrc][usercmd][reference-move][framing]") {
    const g::GoldSrcReferenceClientMoveCodec codec{binding(), 1};
    g::ReferenceMoveSource source;
    source.reliable = true;
    source.fragmented = true;
    auto bytes = hex("03 6e 65 77 00 05 00 00 01 02 04 cc 00 19 50 00 04 12 01");
    const auto decoded = g::decode_reference_client_payload(codec, bytes, source);
    REQUIRE_FALSE(decoded.error);
    REQUIRE(decoded.moves.size() == 1);
    CHECK(decoded.end_byte == bytes.size());
    CHECK(decoded.moves[0].start_byte == 9);
    CHECK(decoded.moves[0].end_byte == 16);
    CHECK(decoded.moves[0].source.reliable);
    bytes.push_back(std::byte{0xfe});
    bytes.push_back(std::byte{2}); // No scan to this move-like byte.
    const auto stopped = g::decode_reference_client_payload(codec, bytes, source);
    REQUIRE(stopped.error);
    CHECK(stopped.error->code == g::ReferenceMoveErrorCode::unsupported_boundary);
    CHECK(stopped.error->bit_offset == 19 * 8);
    CHECK(stopped.moves.empty());
    CHECK(stopped.end_byte == 19);
    CHECK(g::decode_reference_client_payload(codec, hex("03 61"), source)
              .error.has_value());
    CHECK(
        g::decode_reference_client_payload(codec, hex("04"), source).error.has_value());
    CHECK(g::decode_reference_client_payload(codec, hex("01 01"), source, {62, 2048, 1})
              .error.has_value());
    // This pure API has no driver/socket/history parameter, and cannot submit.
    source.generation = 9;
    CHECK(
        g::decode_reference_client_payload(codec, hex("01"), source).error.has_value());
    source.generation = 1;
    const auto duplicate = g::decode_reference_client_payload(
        codec, hex("02 04 cc 00 19 50 00 02 04 cc 00 19 50 00"), source);
    REQUIRE(duplicate.error);
    CHECK(duplicate.error->code == g::ReferenceMoveErrorCode::duplicate_move);
    CHECK(duplicate.moves.empty());
}

TEST_CASE("Reference masks may be redundant without changing owning commands",
          "[goldsrc][usercmd][reference-move][representation]") {
    const g::GoldSrcReferenceClientMoveCodec codec{binding(), 1};
    g::ReferenceMoveSource source;
    for (const auto text :
         {"02 05 bf 01 19 50 00 00",       // nonminimal empty mask
          "02 06 92 11 19 50 00 00 00",    // explicit unchanged msec
          "02 06 94 01 19 50 00 09 00"}) { // signed negative zero forward
        const auto literal = hex(text);
        const auto decoded = codec.decode(literal, 0, source);
        REQUIRE(decoded);
        REQUIRE(decoded.message->commands.size() == 1);
        CHECK(decoded.message->commands[0].value == g::GoldSrcWireUserCmd{});
        const std::array commands{decoded.message->commands[0].value};
        const auto encoded = codec.encode(commands, 0, 0, source);
        REQUIRE(encoded);
        CHECK(encoded.message->bytes == hex("02 04 cc 00 19 50 00"));
        CHECK(encoded.message->bytes != literal);
    }
    source.sequence = 0x11223344;
    const auto limited = g::decode_reference_client_payload(
        codec, hex(complex_wire), source, {62, 2048, 1024, 2});
    REQUIRE(limited.error);
    CHECK(limited.error->code == g::ReferenceMoveErrorCode::count_limit);
    CHECK(limited.moves.empty());
}

TEST_CASE("Reference schema binding checks wire facts without native offsets or "
          "opening strict gates",
          "[goldsrc][usercmd][reference-move][schema]") {
    namespace f = hlclient::test::usercmd_fixture;
    auto fields = f::kExactFields;
    fields[0].offset = 600;
    auto registry = f::registry_from_fields(fields);
    auto reference = g::bind_goldsrc_usercmd_schema(
        registry,
        g::GoldSrcUserCmdSchemaBindingProfile::public_goldsrc48_usercmd_schema_v1);
    REQUIRE(reference);
    CHECK(reference.binding->entries()[0].encode_support ==
          g::GoldSrcUserCmdFieldCodecSupport::public_reference);
    CHECK_FALSE(g::bind_goldsrc_usercmd_schema(registry));
    CHECK_FALSE(g::bind_goldsrc_usercmd_schema(
        registry, g::GoldSrcUserCmdSchemaBindingProfile::
                      stock_protocol_48_build_10210_schema_only));
    fields = f::kExactFields;
    fields[4].type |= 0x80000000U;
    auto wrong_type = f::registry_from_fields(fields);
    CHECK_FALSE(g::bind_goldsrc_usercmd_schema(
        wrong_type,
        g::GoldSrcUserCmdSchemaBindingProfile::public_goldsrc48_usercmd_schema_v1));
    fields = f::kExactFields;
    fields[5].premultiply = 8000;
    auto wrong_scale = f::registry_from_fields(fields);
    CHECK_FALSE(g::bind_goldsrc_usercmd_schema(
        wrong_scale,
        g::GoldSrcUserCmdSchemaBindingProfile::public_goldsrc48_usercmd_schema_v1));
    const auto synthetic = g::bind_goldsrc_usercmd_schema(f::exact_registry());
    REQUIRE(synthetic);
    CHECK_FALSE(g::GoldSrcReferenceClientMoveCodec{*synthetic.binding, 1}
                    .valid_configuration());
    const g::GoldSrcClientMoveMessageCodec old_api{
        {}, g::GoldSrcClientMoveCompatibilityProfile::public_goldsrc48_client_move_v1};
    CHECK_FALSE(
        old_api
            .valid_configuration()); // No route through synthetic planner/transmission.
}
