include_guard(GLOBAL)

# Check CMake's actual graph, not spelling conventions in CMakeLists.txt.
# Generator-expression branches are conservatively considered dependencies.
function(_hlclient_boundary_targets directory result)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        _hlclient_boundary_targets("${child}" child_targets)
        list(APPEND targets ${child_targets})
    endforeach()
    set(${result} "${targets}" PARENT_SCOPE)
endfunction()

function(_hlclient_boundary_resolve target result)
    get_target_property(alias "${target}" ALIASED_TARGET)
    if(alias)
        set(${result} "${alias}" PARENT_SCOPE)
    else()
        set(${result} "${target}" PARENT_SCOPE)
    endif()
endfunction()

function(_hlclient_boundary_dependencies target result)
    set(dependencies)
    foreach(property IN ITEMS LINK_LIBRARIES INTERFACE_LINK_LIBRARIES
            MANUALLY_ADDED_DEPENDENCIES SOURCES INTERFACE_SOURCES)
        get_target_property(values "${target}" ${property})
        foreach(value IN LISTS values)
            if(property STREQUAL "SOURCES" OR property STREQUAL "INTERFACE_SOURCES")
                # A path such as include/hlclient/core/log.hpp contains the
                # executable name as a directory component, not a dependency.
                string(REGEX MATCHALL "\\$<TARGET_OBJECTS:[^>]+>" expressions "${value}")
                if(NOT expressions)
                    continue()
                endif()
                string(JOIN " " value ${expressions})
            elseif(TARGET "${value}")
                _hlclient_boundary_resolve("${value}" resolved)
                list(APPEND dependencies "${resolved}")
                continue()
            elseif(NOT value MATCHES "\\$<")
                continue() # Ordinary flags, library paths and link keywords.
            endif()
            # Includes $<LINK_ONLY:alias>, conditional links, TARGET_OBJECTS,
            # and interface/monolithic bridge targets.
            string(REGEX REPLACE "\\$<[A-Za-z_][A-Za-z0-9_]*:" " " flattened "${value}")
            string(REGEX MATCHALL "[A-Za-z_][A-Za-z0-9_.:+-]*" tokens "${flattened}")
            foreach(token IN LISTS tokens)
                if(TARGET "${token}")
                    _hlclient_boundary_resolve("${token}" resolved)
                    list(APPEND dependencies "${resolved}")
                endif()
            endforeach()
        endforeach()
    endforeach()
    list(REMOVE_DUPLICATES dependencies)
    set(${result} "${dependencies}" PARENT_SCOPE)
endfunction()

function(_hlclient_boundary_walk target chain)
    _hlclient_boundary_resolve("${target}" resolved)
    if(resolved IN_LIST chain)
        return()
    endif()
    get_property(verified GLOBAL PROPERTY "HLCLIENT_BOUNDARY_TARGET_${resolved}")
    if(verified)
        return()
    endif()
    get_target_property(is_module "${resolved}" HLCLIENT_GAME_MODULE)
    if(is_module)
        message(FATAL_ERROR "Game boundary violation: core dependency ${chain} -> ${resolved}")
    endif()
    list(APPEND chain "${resolved}")
    _hlclient_boundary_dependencies("${resolved}" dependencies)
    foreach(dependency IN LISTS dependencies)
        _hlclient_boundary_walk("${dependency}" "${chain}")
    endforeach()
    set_property(GLOBAL PROPERTY "HLCLIENT_BOUNDARY_TARGET_${resolved}" TRUE)
endfunction()

function(_hlclient_boundary_file file chain)
    if(NOT EXISTS "${file}" OR IS_DIRECTORY "${file}")
        return()
    endif()
    file(REAL_PATH "${file}" absolute)
    file(TO_CMAKE_PATH "${absolute}" absolute)
    if(absolute MATCHES "/(include/hlclient|src)/games/halflife/")
        message(FATAL_ERROR "Game boundary violation: core source/include ${chain} -> ${absolute}")
    endif()
    string(SHA256 key "${absolute}")
    get_property(visited GLOBAL PROPERTY "HLCLIENT_BOUNDARY_FILE_${key}")
    if(visited)
        return()
    endif()
    set_property(GLOBAL PROPERTY "HLCLIENT_BOUNDARY_FILE_${key}" TRUE)
    file(STRINGS "${absolute}" includes REGEX "^[ \t]*#[ \t]*include[ \t]+[<\"]")
    get_filename_component(parent "${absolute}" DIRECTORY)
    foreach(include IN LISTS includes)
        string(REGEX REPLACE "^[ \t]*#[ \t]*include[ \t]+[<\"]([^>\"]+)[>\"].*" "\\1" name "${include}")
        if(name MATCHES "^hlclient/")
            set(child "${PROJECT_SOURCE_DIR}/include/${name}")
        elseif(EXISTS "${parent}/${name}")
            set(child "${parent}/${name}")
        else()
            continue()
        endif()
        _hlclient_boundary_file("${child}" "${chain} -> ${absolute}")
    endforeach()
endfunction()

function(hlclient_check_game_module_boundaries)
    _hlclient_boundary_targets("${PROJECT_SOURCE_DIR}" targets)
    set(core_libraries)
    set(manifest "HLCLIENT_BUILD_GAME_HALFLIFE=${HLCLIENT_BUILD_GAME_HALFLIFE}\n")
    foreach(target IN LISTS targets)
        if(NOT target MATCHES "^hlclient")
            continue()
        endif()
        get_target_property(is_module "${target}" HLCLIENT_GAME_MODULE)
        get_target_property(is_composition "${target}" HLCLIENT_GAME_COMPOSITION)
        get_target_property(type "${target}" TYPE)
        _hlclient_boundary_dependencies("${target}" dependencies)
        get_target_property(sources "${target}" SOURCES)
        get_target_property(interface_sources "${target}" INTERFACE_SOURCES)
        string(APPEND manifest "\n${target} [${type}] module=${is_module} composition=${is_composition}\nlinks=${dependencies}\nsources=${sources};${interface_sources}\n")
        if(is_module)
            # Concrete modules may use shared mechanisms, but must not acquire
            # host/session ownership through an intermediate library.
            set(queue ${dependencies})
            set(visited)
            while(queue)
                list(POP_FRONT queue dependency)
                if(dependency IN_LIST visited)
                    continue()
                endif()
                list(APPEND visited "${dependency}")
                if(dependency STREQUAL "hlclient_game_client_host" OR
                        dependency STREQUAL "hlclient_goldsrc_live_runtime" OR
                        dependency STREQUAL "hlclient_application_runtime_replay")
                    message(FATAL_ERROR "Game boundary violation: concrete module depends on host ${dependency}")
                endif()
                _hlclient_boundary_dependencies("${dependency}" next)
                list(APPEND queue ${next})
            endwhile()
            continue()
        endif()
        if(is_composition)
            continue()
        endif()
        _hlclient_boundary_walk("${target}" "")
        get_target_property(source_directory "${target}" SOURCE_DIR)
        foreach(source IN LISTS sources interface_sources)
            if(source MATCHES "(include/hlclient|src)/games/halflife/")
                message(FATAL_ERROR "Game boundary violation: core source ${target} -> ${source}")
            endif()
            if(source MATCHES "^\\$<")
                continue() # Object-library dependencies already traversed.
            endif()
            if(NOT IS_ABSOLUTE "${source}")
                set(source "${source_directory}/${source}")
            endif()
            _hlclient_boundary_file("${source}" "${target}")
        endforeach()
        if(type STREQUAL "STATIC_LIBRARY" OR type STREQUAL "OBJECT_LIBRARY")
            list(APPEND core_libraries "${target}")
        endif()
    endforeach()
    if(NOT TARGET hlclient_engine_core)
        add_custom_target(hlclient_engine_core DEPENDS ${core_libraries})
        set_property(TARGET hlclient_engine_core PROPERTY FOLDER "Engine")
    endif()
    file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/game-boundary-manifest.txt" CONTENT "${manifest}")
    message(STATUS "Game boundary: actual targets, transitive links, aliases, sources and project includes verified")
endfunction()
